from typing import List

from pydantic import Field

from rm_gallery.core.rm.module import (
    BaseListWisePrincipleReward,
    BasePointWisePrincipleReward,
)
from rm_gallery.core.rm.registry import RewardRegistry

CLASSIFICATION_PRINCIPLES = [
    "high-quality responses in addressing the user’s query ( note that the definition of ‘a high-quality response’ can be task-specific; generally speaking, it can be practical, accurate, comprehensive and educational, etc.);",
    "clarity and conciseness of language;",
    "If the intention of the task is vague, infer the intention or ask follow-up questions for clarification.",
]


@RewardRegistry.register("classification_helpful_pointwise")
class ClassificationPointWiseReward(BasePointWisePrincipleReward):
    desc: str = """Please act as an unbiased and impartial evaluator tasked with assessing the quality of the responses provided below.
You will be given the answer generated by an AI assistant in response to a user’s query.
You should critically and accurately assess the assistant’s answer with the key principles to be a qualified response without any potential bias.
"""

    principles: List[str] = Field(default=CLASSIFICATION_PRINCIPLES)


@RewardRegistry.register("classification_helpful_listwise")
class ClassificationListWiseReward(BaseListWisePrincipleReward):
    desc: str = """Please act as an impartial judge and evaluate the quality of the answers provided by some assistants to the user question displayed below.
You should critically and accurately assess the assistant’s answer with the key principles to be a qualified response without any potential bias and choose the assistant that follows the user’s query and answers the user’s question best.
Avoid any position biases and ensure that the order in which the responses were presented does not influence your decision.
Do not allow the length of the responses to influence your evaluation.
Do not favor certain names of the assistants.
Be as goal as possible.

# Scenario
A classification task pecifically includes the following types:
1. Content Categorization: Correctly identifies and categorizes the text ’ s topic, style, or genre, such as accurately classifying an article as technology, art, or business,
2. Quality and Compliance Assessment: Evaluates whether the text adheres to established standards and regulations, identifying specific areas of non-compliance.
"""

    principles: List[str] = Field(default=CLASSIFICATION_PRINCIPLES)
