dataset:
    name: helpsteer2_pointwise                   # dataset name(local: renwardbench2, huggingface: allenai/reward-bench-2)
    configs:
        type: local                       # data source type: local/huggingface
        source: helpsteer2_pointwise              # data source identifier(need to ensure the converter is registered)
        path: ./data/HelpSteer2/train.jsonl      # data file path(only valid when local)
    export:                               # export configuration
        output_dir: ./examples/data/exports # export path
        formats: ["parquet"]                # supported formats: jsonl, parquet, json
        preserve_structure: true          # control whether to preserve the original directory structure when exporting data
        split_ratio: {"train": 0.8, "test": 0.2} # split training and test sets


